### ISSUE TITLE
Bildgrößen Startseite

### ISSUE THREAD

**Issue by TomasKostadinov** [ToKoSoftware/dhbw-svm-portal#1]
Wenn die Startseite Mobil aufgerufen wird sind alle Bilder unterschiedlich groß.

**Comment by TomasKostadinov** [comment]
![grafik](https://user-images.githubusercontent.com/11008743/102100627-f3cfdf80-3e29-11eb-8744-efd06e7498ae.png)

**Comment by leokndlr** [comment]
![svm3 services kostadinov it_](https://user-images.githubusercontent.com/56634709/104023603-320ab580-51c2-11eb-8721-be5f05d6d8d5.png)

Passt das? @TomasKostadinov
