### ISSUE TITLE
Kalenderfunktion

### ISSUE THREAD

**Issue by TomasKostadinov** [ToKoSoftware/dhbw-svm-portal#10]
"Verwendung einer Kalenderfunktion zur Jahresplanungauf der Startseite / Home"

-> Joomla oder Google Kalender per Iframe

**Comment by leokndlr** [comment]
1. Google Kalender erstellt
2. Google Kalender personalisiert 
3. IFrame/HTML kopiert 
4. Article in Joomla geöffnet
5. HTML in IFrame eingebettet (Einstellungen in Joomla geändert unter anderem meinen Editor verändert, damit Code bearbeitet werden konnte) 
6. Kalender auf width="100%"
