### ISSUE TITLE
Umfragen

### ISSUE THREAD

**Issue by TomasKostadinov** [ToKoSoftware/dhbw-svm-portal#11]
Umfragen

- Admins können Umfragen anlegen, bearbeiten, löschen
- User können teilnehmen

DB: Poll

-> Soll es gratis Eis geben?
- Grafische Darstellung der Ergebnisse
- CSV Export von Teilnehmerliste
- Titel, Beschreibung, Ablaufdatum, is_active

- [x] CREATE

- [x] READ

- [x] UPDATE

- [x] DELETE

DB: PollOption

-> Ja
- Titel, PollId

- [x] CREATE

- [x] READ

- [x] UPDATE

- [x] DELETE

DB: PollVote

-> Tomas hat Ja abgestimmt

- UserID, PollOptionID, CreatedAt, UpdatedAt, Bemerkung
- für eigenen User
- Ablaufdatum beachten
- Kann nur einmal pro PollId abgegeben werden

- [x] CREATE

- [x] READ

- [x] UPDATE

- [x] DELETE

**Comment by DominikRuf** [comment]
Alles implementiert.
Recht in entsprechendem Issue
