### ISSUE TITLE
Joomla Website - Bildergallerie mit Zugang beschränken

### ISSUE THREAD

**Issue by TomasKostadinov** [ToKoSoftware/dhbw-svm-portal#12]
Joomla Plugin um einzelne Seite mit Passwort zu schützen

-> Passwort wird im Internen Bereich angezeigt

**Comment by leokndlr** [comment]
Habe Access auf "Registered" gemacht, nun muss sich derjenige/diejenige der/die die Galerie einsehen möchte, sich anmelden. Mit einer E-Mail Adresse und einem Username. Später muss er/sie per Mail die Registration bestätigen und ein Admin muss in Joomla im Backend den User zulassen.

**Comment by leokndlr** [comment]
![IMG_A963A4C33162-1](https://user-images.githubusercontent.com/56634709/105579029-2e5f5d00-5d84-11eb-9c5b-af9744a308ca.jpeg)
So sieht das Anmeldefenster aus, wenn man auf Bilder klickt.

**Comment by leokndlr** [comment]
<img width="788" alt="Bildschirmfoto 2021-01-23 um 13 48 05" src="https://user-images.githubusercontent.com/56634709/105579051-58b11a80-5d84-11eb-9439-b39deaceb66a.png">
so sieht die Mail aus, die der User bekommt.

**Comment by leokndlr** [comment]
Bitte noch jemand mit einer anderen Mail probieren, nicht mit der mit welcher ihr bereits bei Joomla registriert habt und dann bitte jemand das abchecken und den Issue dann schließen danke:) (ich hab die Mail meiner Schwester missbraucht hehe)

**Comment by leokndlr** [comment]
leider nur über Interner Login möglich .... Bilder wird nicht in Navigationsleiste angezeigt.

**Comment by leokndlr** [comment]
Bilder hinter Login: 
1. Menu Item als Login Form erstellen 
2. Auf Options gehen
3. Choose Login Redirect Type auf "Internal URL" 
4. Login Redirect: URL von Bildergalerie einfügen
5. Et voila
