### ISSUE TITLE
Layout improvements - Rollen

### ISSUE THREAD

**Issue by BlueEnni** [ToKoSoftware/dhbw-svm-portal#124]
![Screenshot 2021-02-03 222654](https://user-images.githubusercontent.com/15313485/106811776-1c789680-666f-11eb-94de-5ef179263d8d.png)

Is it on purpose, that all users of a specific role can be (according to the symbols) 'edited' or 'deleted'?

**Comment by TomasKostadinov** [comment]
Disabled the role deletion, edit role has been implemented
