### ISSUE TITLE
Layout improvements - Registration

### ISSUE THREAD

**Issue by BlueEnni** [ToKoSoftware/dhbw-svm-portal#126]
![Screenshot 2021-02-03 224152](https://user-images.githubusercontent.com/15313485/106813452-4a5eda80-6671-11eb-9e2d-55760a116691.png)

We need to add a 'lable' to the background of the textbox. (E.g. Mat-lable: https://material.angular.io/components/form-field/overview)

**Comment by TomasKostadinov** [comment]
Wird mit der #45 gefixt
