### ISSUE TITLE
News

### ISSUE THREAD

**Issue by TomasKostadinov** [ToKoSoftware/dhbw-svm-portal#13]
Als Admin News Posten, welchen dann im intern Bereich auftauchen

- Admins können News anlegen, bearbeiten, löschen

DB: News

- Titel, Beschreibung (Markdown), is_active

- [ ] CREATE

- [ ] READ

- [ ] UPDATE

- [ ] DELETE

**Comment by DominikRuf** [comment]
Wird in einzelnen Issues abgehandelt
