### ISSUE TITLE
Dummy Bilder austauschen

### ISSUE THREAD

**Issue by DominikRuf** [ToKoSoftware/dhbw-svm-portal#132]
Bilder und Icon hochladen

**Comment by TomasKostadinov** [comment]
https://github.com/ToKoSoftware/dhbw-svm-outdoor

**Comment by leokndlr** [comment]
@TomasKostadinov @DominikRuf habe jetzt mal geeignete Bilder ausgesucht.

**Comment by leokndlr** [comment]
> Bilder und Icon hochladen

Icons sind nun auch vorhanden.

**Comment by TomasKostadinov** [comment]
Danke fürs hochladen, habe noch die öffentlichen Bilder auf Guest only gestellt, dann verschwindet der Menüpunkt
