### ISSUE TITLE
Adding a user to a team does not work - frontend -> backend 

### ISSUE THREAD

**Issue by BlueEnni** [ToKoSoftware/dhbw-svm-portal#136]
![add member to team - geht noch nicht](https://user-images.githubusercontent.com/15313485/107219516-813a4500-6a11-11eb-8cc2-750378b85819.png)

Adding a user to a team does not work, frontend -> backend  (as admin)

**Comment by TomasKostadinov** [comment]
Permission problem, @DominikRuf kümmert sich

**Comment by TomasKostadinov** [comment]
@BlueEnni falls behoben bitte issue schließen

**Comment by BlueEnni** [comment]
Issue seems to be resolved on the current main branch
