### ISSUE TITLE
Adding a user to a role does not work - frontend -> backend 

### ISSUE THREAD

**Issue by BlueEnni** [ToKoSoftware/dhbw-svm-portal#137]
![add user to role does not work](https://user-images.githubusercontent.com/15313485/107219807-e130eb80-6a11-11eb-9d24-d8db19b0c90b.png)

Adding a user to a role does not work, frontend -> backend (as a admin)

**Comment by TomasKostadinov** [comment]
Sollte gefixt sein, @BlueEnni bitte überprüfen und dann issue schließen :)

**Comment by BlueEnni** [comment]
Everything seems to be working now^^ - but I have another suggestion, which I will describe in a new issue
