### ISSUE TITLE
Feature-Request: Adding filters for the statistic page - frontend

### ISSUE THREAD

**Issue by BlueEnni** [ToKoSoftware/dhbw-svm-portal#138]
![adding filters to statistics - week - day - hour](https://user-images.githubusercontent.com/15313485/107219970-12112080-6a12-11eb-9c17-5395dbbff1c5.png)

I think it would be nice to add filters for the statistic page (users per hour/day/week)

**Comment by TomasKostadinov** [comment]
Nicht mehr im scope
