### ISSUE TITLE
Feature-Request: Adding a user via the management page does not work - frontend -> backend 

### ISSUE THREAD

**Issue by BlueEnni** [ToKoSoftware/dhbw-svm-portal#139]
![adding users only via registration possible - is that intentional](https://user-images.githubusercontent.com/15313485/107220300-78963e80-6a12-11eb-8046-1b2c6d81bf33.png)

I think it would be nice, being able to create dummy users via the user-management page as an administrator.

**Comment by TomasKostadinov** [comment]
Nicht mehr im scope
