### ISSUE TITLE
Filtering for the given fields does not work - frontend

### ISSUE THREAD

**Issue by BlueEnni** [ToKoSoftware/dhbw-svm-portal#140]
![filtering users does not work](https://user-images.githubusercontent.com/15313485/107220636-e478a700-6a12-11eb-885d-e33e8601cd07.png)

Filtering for the given fields does not work, frontend -> backend (as admin)

**Comment by TomasKostadinov** [comment]
Da wir das vor der Abgabe nicht mehr schaffen erscheint nun ein Popup, wenn diese Funktion verwendet wird. Muss in zukunft angepasst werden.
