### ISSUE TITLE
Saving another organization name does not work - frontend -> backend 

### ISSUE THREAD

**Issue by BlueEnni** [ToKoSoftware/dhbw-svm-portal#141]
![saving a new organization name does not give the user any visual feedback and seems to not work](https://user-images.githubusercontent.com/15313485/107220865-2570bb80-6a13-11eb-9f21-d68e9d00bba7.png)

Saving another organization name does not work, nor does a feedback (e.g. snakebar) pop up, wether it has been successful or not

**Comment by TomasKostadinov** [comment]
You need to change the access code, that's an backend error

**Comment by BlueEnni** [comment]
We should notify if the access_code field was left empty in an "err message" popup
