### ISSUE TITLE
Feature-Request: Popup after trying to save an organization without access_code

### ISSUE THREAD

**Issue by BlueEnni** [ToKoSoftware/dhbw-svm-portal#151]
![image](https://user-images.githubusercontent.com/15313485/107408051-b6768e00-6b0a-11eb-832b-fe2b095d5894.png)

We should notify the user if the access_code field was left empty (while trying to save the organization) in an "err message" popup (e.g. with a snakebar)

**Comment by TomasKostadinov** [comment]
Wurde behoben
