### ISSUE TITLE
Texte für Abschluss-Präsentation

### ISSUE THREAD

**Issue by TomasKostadinov** [ToKoSoftware/dhbw-svm-portal#155]
Wir benötigen 

- [x] 2 Event-Beschreibungstexte, gern mit Tabelle, jeweils einem Bild, einfach Was ausdenken (Silvesterlauf? ...)
- [x] 2 News auch mit Foto oder so (Grillen?)
- [x] 2 Umfragen (Neue Vereinskleidung?)
- [x] Datenschutztext
- [ ] Lastschriftmandattext #200 

jeweils im Markdownformat. Einfach neuen Ordner `presets` unter Dokumentation einfügen und dann jeweils ein Event, News, ... in eine Markdown Datei.

**Comment by BlueEnni** [comment]
2x Event, 2x News, 2x Umfragen sind im #162 fertiggestellt worden.

**Comment by BlueEnni** [comment]
Hatten wir nicht schon einen Datenschutztext in unserer alten Website?

**Comment by TomasKostadinov** [comment]
ist ja noch online - https://svm3.services.kostadinov.it/ @BlueEnni

**Comment by DominikRuf** [comment]
https://svm3.services.kostadinov.it/datenschutz @BlueEnni

**Comment by BlueEnni** [comment]
#196 Datenschutzerklärung
