### ISSUE TITLE
Issue Bucket for Portal auffälligkeiten

### ISSUE THREAD

**Issue by Urs-sein-github** [ToKoSoftware/dhbw-svm-portal#198]
- Veranstaltungen werden durch speichern erstellt. man bleibt beim Fenster und erstellt sie öfters durch klicken. (nicht schlimm)

- Als Team-Maintaintaimer kann man Veranstaltungen für "Jeden auch extern" erstellen aber nicht verwalten. Denke nicht schlimm aber joa.

- Links in Veranstaltungen werden im Gleichen Fenster geöffnet.

- Gläubiger Identifikationsnummer haben wir nicht. Sollte man halt irgendwo aufschreiben, dass sie das adden muss/soll/kann.

**Comment by TomasKostadinov** [comment]
>Veranstaltungen werden durch speichern erstellt. man bleibt beim Fenster und erstellt sie öfters durch klicken. (nicht schlimm)


Close Slideover nach event create
