### ISSUE TITLE
Webseite aufräumen

### ISSUE THREAD

**Issue by TomasKostadinov** [ToKoSoftware/dhbw-svm-portal#2]
- Design vereinheitlichen (Tabellen von Terminen, Trainingszeiten)
- Alle Links überprüfen

**Comment by TomasKostadinov** [comment]
Vereinheitlichen von Desktop und Mobiler Version

**Comment by DominikRuf** [comment]
![image](https://user-images.githubusercontent.com/56634563/107624918-d6699700-6c5b-11eb-9859-8192e4d05e86.png)
