### ISSUE TITLE
SSO (Single Sign On) über Joomla

### ISSUE THREAD

**Issue by TomasKostadinov** [ToKoSoftware/dhbw-svm-portal#3]
Prüfen, ob die User-Daten um weitere Felder erweitert werden können

**Comment by TomasKostadinov** [comment]
http://www.passportjs.org/packages/passport-saml/

**Comment by leokndlr** [comment]
> http://www.passportjs.org/packages/passport-saml/

ich versteh nicht so ganz was das ist und wo ich den Code einbetten soll? Weißt du da was?

**Comment by leokndlr** [comment]
Ich meine natürlich dich @TomasKostadinov

**Comment by TomasKostadinov** [comment]
@leokndlr Das Passport js ist für die Gegenseite, also für das Portal
Es muss für Joomla ein Plugin geben, welches Joomla einen anderen Server als Identity Provider akzeptieren lässt
