### ISSUE TITLE
Lastschriftmandat

### ISSUE THREAD

**Issue by TomasKostadinov** [ToKoSoftware/dhbw-svm-portal#36]
Der Verein möchte, dass der User ein Lastschriftmandat zur Automatischen Abbuchung erteilen kann

**Comment by DominikRuf** [comment]
- neue Relation DirectDebitMandate mit 
  - IBAN
  - user_id
  - org_id
  - bank_name
- Auf Org: 
  - markdown field für  DirectDebitMandateContractText
  - Field CI: Gläubiger-Identifikationsnummer

**Comment by DominikRuf** [comment]
Der Inhalt eines SEPA-Lastschriftmandats ist durch das „SEPA Direct Debit Core Rulebook“[30], vom European Payments Council (EPC) vorgegeben:

- Überschrift
- Mandatsreferenz (vergeben vom Gläubiger)
- Name und Logo des Gläubiger
- Autorisierung durch den Zahler: Einzugsermächtigung und Weisung zur Einlösung an die Bank des Zahlers
- Hinweis auf das Erstattungsrecht von 8 Wochen
- Angaben zum Zahler
- Weitere Angaben zum Gläubiger
- Zahlungsart: Einmalig oder wiederkehrend
- Ort und Datum der Unterschrift
- Unterschrift des Zahlers
- Angaben zum Vertragsverhältnis zwischen Gläubiger und Zahler

**Comment by DominikRuf** [comment]
Jedes SEPA-Lastschriftmandat muss folgende Angaben enthalten:

- Bezeichnung des Zahlungsempfängers,
- eine Gläubiger-Identifikationsnummer (CI),
- Name des Kunden (Zahler),
- Bezeichnung der Bank des Kunden (Zahler) und
- seine Kundenkennung (IBAN).
