### ISSUE TITLE
Kontakte Seite neu anlegen / Custom CSS schreiben

### ISSUE THREAD

**Issue by TomasKostadinov** [ToKoSoftware/dhbw-svm-portal#4]

**Comment by TomasKostadinov** [comment]
![Bildschirmfoto 2020-12-14 um 16 36 25](https://user-images.githubusercontent.com/11008743/102101099-83758e00-3e2a-11eb-916d-5427e1462ef7.png)

**Comment by leokndlr** [comment]
Könnt ihr mal schauen?

**Comment by TomasKostadinov** [comment]
@leokndlr kannst gern @TomasKostadinov  verwenden, dann bekomm ich ne nachricht

Sieht schonmal gut aus, kannst du noch die Schriftgrößen und Bilder (z.b. der Rand um das Bild) an den Rest der Seite anpassen?

**Comment by TomasKostadinov** [comment]
![Bildschirmfoto 2021-01-07 um 17 48 13](https://user-images.githubusercontent.com/11008743/103919608-85243000-5110-11eb-836d-7b272178ada6.png)

Mobil ist noch bisschen komisch

**Comment by leokndlr** [comment]
<img width="435" alt="Bildschirmfoto 2021-01-08 um 14 40 14" src="https://user-images.githubusercontent.com/56634709/104021838-c1fb3000-51bf-11eb-9f32-b3866c5f07c3.png">
So mobil bricht es jetzt schön um und die Ränder sind weg. Schriftgröße ist wie bei anderen Unterseiten beim Haupttext 1rem. 
Passt das so? @TomasKostadinov

**Comment by TomasKostadinov** [comment]
Bitte die Code Änderungen noch per Pull-Request hier einfügen https://github.com/ToKoSoftware/dhbw-svm-outdoor-joomla @leokndlr

**Comment by leokndlr** [comment]
https://github.com/ToKoSoftware/dhbw-svm-outdoor-joomla/pull/1
