### ISSUE TITLE
Portal auf Website verlinken

### ISSUE THREAD

**Issue by TomasKostadinov** [ToKoSoftware/dhbw-svm-portal#5]

**Comment by TomasKostadinov** [comment]
@leokndlr wie ist hier der stand? kann das geschlossen werden?

**Comment by leokndlr** [comment]
ich glaube ja, also wie ich mal in die Gruppe geschrieben habe.

**Comment by TomasKostadinov** [comment]
Also wie besprochen - bitte noch einen Logout Link einfügen :)

**Comment by leokndlr** [comment]
@TomasKostadinov ist erledigt. Kannst du schauen ob das so passt? Dankee!
