### ISSUE TITLE
Projekt-Dokumentation

### ISSUE THREAD

**Issue by DominikRuf** [ToKoSoftware/dhbw-svm-portal#54]
<table>
<tr>
	<td width="33%">
 Problemstellung, Userstories, Lösungsansatz (Wir haben ein CMS genommen, Portal entwicklent, Frameworks, Rest-Api, Datenbank)
	<td>
4 Seiten
	<td>
	Lösungsansatz @DominikRuf <br/>
@LisaFremdt 
<tr>
	<td>
Projektmanagement (Github Boards, Doing, Done, Zeitplanung, Issues, Pull request, Review) 
	<td>
~2 Seiten
	<td>
@LisaFremdt 
<tr>
	<td>
Frontend
	<td>
4 Seiten
	<td>
@TomasKostadinov 
<tr>
	<td>
Backend + Rückblick
	<td>
4 Seiten
	<td>
@DominikRuf 
<tr>
	<td>
Error Handling
	<td>
~1-2 Seiten
	<td>
@BlueEnni 
<tr>
	<td>
Joomla (Kalender, Plugins, SSO mit Oauth2)
	<td>
4 Seiten
	<td>
@leokndlr 
<tr>
	<td>
ER Modell (Zu jeder Entität und jeder Verbindung und jedem Attribut etwas schreiben)
	<td>
2 Seiten
	<td>
@Urs-sein-github  
<tr>
	<td>
Ausblick und Fazit
	<td>
2 Seiten
	<td>
@BlueEnni 
</table>

**Comment by TomasKostadinov** [comment]
Interne Deadline 07.03
