### ISSUE TITLE
Anmeldung zu Events

### ISSUE THREAD

**Issue by TomasKostadinov** [ToKoSoftware/dhbw-svm-portal#7]
Ein Event ist z.B. eine Sportveranstaltung

- Admins können Events anlegen, bearbeiten, löschen
- User können sich selbst anmelden

DB: Event

- Titel, Beschreibung (Markdown), Adresse/Ort, Datum Beginn, Datum Ende, Max Teilnehmerzahl, Anmeldeschluss, Verantwortlicher User, is_active

- [ ] CREATE

- [ ] READ

- [ ] UPDATE

- [ ] DELETE

DB: EventRegistration
- UserID, CreatedAt, UpdatedAt, Bemerkung
- für eigenen User
- Als Admin ein anderen User anmelden
- Max. Teilnehmerzahl beachten
- CSV Export von Teilnehmerliste

- [ ] CREATE

- [ ] READ

- [ ] UPDATE

- [ ] DELETE

**Comment by DominikRuf** [comment]
Wird in einzelnen Issues behandelt.
