### ISSUE TITLE
Vorschau Bildergalerie löschen 

### ISSUE THREAD

**Issue by leokndlr** [ToKoSoftware/dhbw-svm-portal#97]

**Comment by leokndlr** [comment]
Auf unpublished gestellt.

**Comment by TomasKostadinov** [comment]
Können wir vielleicht einige Bilder trotzdem öffentlich lassen? Bzw. einfach eine Gallerie haben, welche "Öffentlich" ist?
@leokndlr

**Comment by TomasKostadinov** [comment]
Ist implementiert
